### ISSUE TITLE
SQL migrate does not complete

### ISSUE THREAD

**Issue by seznam-expatcz** [McLive/DjangoPowerDNS#14]
Hi McLive,

I've tried to get DjangoPowerDNS running, but unfortunately, SQL migrate returns an error.
I've tried several Ubuntu installations (14, 16,18) as well as centos 7 running in vagrant-testkitchen. Also the former django version used before the latest commit. But the error persists. I've created the djangopowerdns db manually at 1st

```create database djangopowerdns;```

After that called the migrations:

```^C(venv) root@default-ubuntu-1404:~/DjangoPowerDNS# python manage.py migrate
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dpdns, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying dpdns.0001_initial...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/root/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/root/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/root/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/root/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/root/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/root/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/root/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 109, in __exit__
    self.execute(sql)
  File "/root/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/root/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/root/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/root/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/root/venv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/root/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1005, "Can't create table 'powerdns.#sql-1b46_37' (errno: 150)")
```

Do you have an idea what could cause this?

**Comment by seznam-expatcz** [comment]
Hi McLive,

true, I forgot this completely. I've recreated the database, applied the the SQL from

[pdns documentation ](https://doc.powerdns.com/authoritative/guides/basic-database.htm) and called 

```python manage.py migrate ``` again. It ran without issues and I could start the server afterwards.
However, the UI itself complains now about missing columns in the database:

```
Request Method: | GET
-- | --
http://192.168.20.11/domains/
1.11.18
OperationalError
(1054, "Unknown column 'records.change_date' in 'field list'")
/root/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py in execute_sql, line 899
/root/venv/bin/python
2.7.6
['/root/DjangoPowerDNS',  '/root/venv/lib/python2.7',  '/root/venv/lib/python2.7/plat-x86_64-linux-gnu',  '/root/venv/lib/python2.7/lib-tk',  '/root/venv/lib/python2.7/lib-old',  '/root/venv/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/root/venv/local/lib/python2.7/site-packages',  '/root/venv/lib/python2.7/site-packages']
Tue, 5 Feb 2019 11:34:12 +0000
```


I've checked the powerdns db, indeed they aren't there. Checked 0001_initial.py in the migrations directory. The SQL code for the missing colums is there. It just seems, it's not applied to the database? Verbose output of ```python manage.py migrate``` does not tell anything useful and completes without error.

Am I doing something wrong?

**Comment by McLive** [comment]
I guess that happened because you recreated the database and now the 0001_initial.py Migration is lost which you already applied earlier. 

I can try to reproduce that later. For now you could try to start over once Ägäis.

**Comment by McLive** [comment]
Thanks, I'll look into that!
